version: '3.8'

services:
  qr-scanner:
    build: .
    container_name: qr_scanner_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      - PYTHONUNBUFFERED=1
